
:- module(problemHolyGrail, [problem/2]).

problem(tias, problem(4, 4, [
        % "The 4 people were Tatum, the patient who was prescribed enalapril, the employee with the $54,000 salary, and the owner of the purple house",
% CHANGED TO: ( "with the salary")
        "The 4 people were tatum, the patient who was prescribed enalapril, the employee who earns 54000, and the owner of the purple house",
        "The patient who was prescribed enalapril is not heather",
        "The patient who was prescribed ramipril is not annabelle",
        "kassidy earns less than heather",
        "The owner of the blue house earns more than kassidy",
%%    "Of tatum and annabelle, one earns 144000 per year and the other lives in the cyan colored house",
%% CHANGED TO: (drop: colored)
        "Of tatum and annabelle, one earns 144000 per year and the other lives in the cyan house",
%%        "Either the employee with the 144000 salary or the employee with the 158000 salary lives in the blue colored house",
%% CHANGED TO: (drop colored, change the ...salara) 
        "Either the employee who earns 144000  or the employee who earns 158000 lives in the blue house",
        "The owner of the lime house was prescribed enalapril for their heart condition",
%%        "The employee with the 144000 salary was prescribed benazepril for their heart condition"
%% CHANGED TO:
        "The employee who earns 144000 was prescribed benazepril for their heart condition"
                     ], [
                        noun([patient], [patients]),
                        noun([person], [people]),
                        noun([year], [years]),
                        noun([employee], [employees]),
                        noun([salary], [salaries]),
                        noun([owner], [owners]),
                        pn([tatum]),
                        pn([annabelle]),
                        pn([heather]),
                        pn([kassidy]),
                        pn([benazepril]),
                        pn([enalapril]),
                        pn([ramipril]),
                        pn([fosinopril]),
                        prep([of]),
                        ppn([the, blue, house]),
                        ppn([the, lime, house]),
                        ppn([the, cyan, house]),
                        ppn([the, purple, house]),
                        tv([owns], [own]),
                        tvGap([earns], [per, year], [earn]),
                        tvGap([was, prescribed], [for, their, heart, condition], [prescribe]),
                        tvPrep([lives], [in], [live], [lived])
                     ])).

problem(p2_types, problem(4,5, [
                        "Of the contestant who scored 41 points and the person who threw the white darts, one was from Worthington and the other was Ira",
                        "Bill was from Mount union",
                        "Ira scored 21 points higher than the contestant from Worthington",
                        "Oscar scored somewhat higher than the player who threw the orange darts",
                        "The contestant from Mount union threw the black darts",
                        "Pedro didn't finish with 55 points",
                        "The player who threw the red darts was either Colin or the contestant who scored 48 points",
                        "Of the contestant who scored 41 points and the person who threw the orange darts, one was from Gillbertville and the other was from Worthington",
                        "Ira scored 7 points lower than the player from Lohrville"
        ], [
                        noun([contestant], [contestants]),
                        noun([person], [persons]),
                        noun([player], [players]),
                        noun([point], [points]),
                        pn([bill], A),
                        pn([colin], A),
                        pn([ira], A),
                        pn([oscar], A),
                        pn([pedro], A),
                        pn([mount, union], B),
                        pn([gillbertville], B),
                        pn([lohrville], B),
                        pn([worthington], B),
                        pn([yorktown], B),
                        ppn([the, black, darts], C),
                        ppn([the, orange, darts], C),
                        ppn([the, red, darts], C),
                        ppn([the, white, darts], C),
                        ppn([the, yellow, darts], C),
                        tv([threw], [throw]),
                        tv([scored], [score]),
                        tvPrep([finishes], [with], [finish], [finished]),
                        prep([from])
        ])).
    
problem(cookies_for_love, problem(5, 4, [
        "jackie 's last name was n't fredericks the cookies sold at bake sale were to help the cook family ",
        "the ginger snap cookies were not baked to help the hatfield family june whose last name was n't baker sponsored the adams family ",
        "ms smith whose first name was n't joyce made the chocolate chip cookies but she did n't sponsor the cook family ",
        "judy levinson did n't sell her cookies at the bake sale the ginger snaps were not baked by the woman sponsoring the adams family ",
        "the peanut butter cookies were banked to help the vanwert family but they were n't sold at the pot luck ",
        "joyce sold her cookies at the school play the sugar cookies were sold before and after sunday church "
                     ], [
    pn([bake]),
    pn([baker]),
    pn([chocolate]),
    pn([church]),
    pn([fredericks]),
    pn([ginger]),
    pn([jackie]),
    pn([joyce]),
    pn([judy]),
    pn([june]),
    pn([levinson]),
    pn([peanut]),
    pn([pot]),
    pn([school]),
    pn([smith]),
    pn([sugar]),
    ppn([the, adams, family]),
    ppn([the, cook, family]),
    ppn([the, hatfield, family]),
    ppn([the, vanwert, family]),
    noun([butter], [butter]),
    noun([chip], [chips]),
    noun([cookies], [cookies]),
    noun([family], [families]),
    noun([luck], [lucks]),
    noun([ms], [mss]),
    noun([name], [names]),
    noun([sale], [sales]),
    noun([snap], [snaps]),
    noun([woman], [women]),
    tv([help], [help]),
    tv([made], [make]),
    tv([sold], [sell]),
    tv([sponsor], [sponsor]),
    tv([sponsored], [sponsor]),
    tv([sponsoring], [sponsor]),
    tvPrep([baked], [by], [bake], [todooo]),
    tvPrep([sold], [at], [sell], [todooo])
                     ])).


problem(expensive_homes, problem(4, 3, [
        "kassandra 's home is worth more than that of the person whose last name is holloway ",
        "the elm tree road resident owns the least valued home ",
        "alexandra lives in neither treelined boulevard nor elm tree road but in the most valued home ",
        "holt is not the last name of the wattle grove resident "
                     ], [
    pn([alexandra]),
    pn([angelo]),
    pn([elm]),
    pn([holloway]),
    pn([holt]),
    pn([kassandra]),
    pn([melton]),
    pn([treelines]),
    pn([wattle]),
    noun([boulevard], [boulevards]),
    noun([grove], [groves]),
    noun([home], [homes]),
    noun([life], [lives]),
    noun([name], [names]),
    noun([person], [people]),
    noun([resident], [residents]),
    noun([road], [roads]),
    noun([tree], [trees]),
    tvPrep([is], [worth], [be], [todooo]),
    tvPrep([lives], [in], [live], [todooo]),
    tvPrep([name], [of], [name], [todooo])
                     ])).


problem(at_the_farm, problem(4, 5, [
        "fran 's day to mend fences is neither tuesday nor thursday and is completed earlier in the week than at least one other person ",
        "the one who goes to market goes later in the week than carl and earlier in the morning than nan but later in the morning than fran ",
        "adam does not plant the corn or go to market his chore is completed before 9am but not before 6am on his assigned day of monday ",
        "no one performs a chore on thursday at 7am ",
        "mike 's chore is completed earlier in the day than at least 3 others but later in the week than at least three others ",
        "one of the boys collects eggs another boy milks bessie the goat ",
        "the milk is collected earlier in the week than the girl who plants the corn which is not planted before wednesday ",
        "the eggs must be collected at 7 am but never on mondays or fridays ",
        "all the other chores must be complete before mike goes to the market "
                     ], [
    pn([adam]),
    pn([carl]),
    pn([corn]),
    pn([eggs]),
    pn([fran]),
    pn([friday]),
    pn([market]),
    pn([mend]),
    pn([mike]),
    pn([milk]),
    pn([monday]),
    pn([nan]),
    pn([thursday]),
    pn([tuesday]),
    pn([wednesday]),
    noun([am], [am]),
    noun([boy], [boys]),
    noun([chore], [chores]),
    noun([day], [days]),
    noun([fence], [fences]),
    noun([friday], [fridays]),
    noun([girl], [girls]),
    noun([goat], [goats]),
    noun([milk], [milks]),
    noun([monday], [mondays]),
    noun([morning], [mornings]),
    noun([one], [ones]),
    noun([other], [others]),
    noun([person], [people]),
    noun([plant], [plants]),
    noun([week], [weeks]),
    tv([collects], [collect]),
    tv([go], [go]),
    tv([goes], [go]),
    tv([plant], [plant]),
    tv([planted], [plant]),
    tv([plants], [plant]),
    tvPrep([collected], [at], [collect], [todooo]),
    tvPrep([complete], [before], [complete], [todooo]),
    tvPrep([completed], [before], [complete], [todooo]),
    tvPrep([planted], [before], [plant], [todooo])
                     ])).


problem(tutorial, problem(4, 4, [
        "the 4 people were tatum the patient who was prescribed enalapril the employee with the 54000 salary and the owner of the purple house ",
        "of tatum and annabelle one earns 144000 per year and the other lives in the cyan house ",
        "the patient who was prescribed enalapril is not heather ",
        "either the employee with the 144000 salary or the employee with the 158000 salary lives in the blue house ",
        "kassidy earns less than heather ",
        "the owner of the blue house earns more than kassidy ",
        "the patient who was prescribed ramipril is not annabelle ",
        "the owner of the lime house was prescribed enalapril for their heart condition ",
        "the employee with the 144000 salary was prescribed benazepril for their heart condition "
                     ], [
    pn([annabelle]),
    pn([benazepril]),
    pn([enalapril]),
    pn([fosinopril]),
    pn([heather]),
    pn([kassidy]),
    pn([ramipril]),
    pn([tatum]),
    ppn([the, blue, house]),
    ppn([the, cyan, house]),
    ppn([the, lime, house]),
    ppn([the, purple, house]),
    noun([condition], [conditions]),
    noun([employee], [employees]),
    noun([heart], [hearts]),
    noun([house], [houses]),
    noun([life], [lives]),
    noun([owner], [owners]),
    noun([patient], [patients]),
    noun([person], [people]),
    noun([salary], [salaries]),
    noun([year], [years]),
    tv([earns], [earn]),
    tv([is], [be]),
    tv([people], [people]),
    tvPrep([lives], [in], [live], [todooo]),
    tvGap([was, prescribed], [for, their, heart, condition], [prescribe])
                     ])).


problem(new_shoes, problem(4, 3, [
        "the pumps were not pink ",
        "the boots were brown but were n't purchased by margaret ",
        "clarisse did n't buy the pumps but spent more than sally ",
        "margaret got the sandals which cost twice as much as sally 's purchase but were n't green "
                     ], [
    pn([boots]),
    pn([brown]),
    pn([clarisse]),
    pn([green]),
    pn([margaret]),
    pn([pink]),
    pn([pumps]),
    pn([sally]),
    pn([sandals]),
    noun([purchase], [purchases]),
    tv([boots], [boot]),
    tv([buy], [buy]),
    tv([got], [get]),
    tv([were], [be])
                     ])).


problem(cats_in_spring, problem(4, 3, [
        "batman chose the female who liked to chase a ball but she was not starbuck ",
        "dibii 's companion liked to chase the laser light ",
        "ruby loved to cuddle up to her male for a long afternoon nap in the sun ",
        "starbuck had two more kittens than batman 's companion "
                     ], [
    pn([ball]),
    pn([batman]),
    pn([dibii]),
    pn([jake]),
    pn([lazer]),
    pn([ruby]),
    pn([sleep]),
    pn([spot]),
    pn([starbuck]),
    noun([afternoon], [afternoons]),
    noun([companion], [companions]),
    noun([female], [females]),
    noun([kitten], [kittens]),
    noun([laser], [lasers]),
    noun([light], [lights]),
    noun([male], [males]),
    noun([nap], [naps]),
    noun([sun], [suns]),
    tv([chase], [chase]),
    tv([had], [have]),
    tv([kittens], [kitten]),
    tv([was], [be]),
    tvPrep([kittens], [than], [kitten], [todooo]),
    tvPrep([nap], [in], [nap], [todooo])
                     ])).


problem(a_bargain, problem(4, 3, [
        "the blue item was not bought by benny ",
        "daniella was pleased to have 900 knocked off the she bought ",
        "the red item had more knocked off than the umbrella ",
        "the trousers did not have 500 knocked off and were not bought by benny or carla "
                     ], [
    pn([benny]),
    pn([carla]),
    pn([daniella]),
    pn([jacket]),
    pn([trousers]),
    pn([umbrella]),
    ppn([the, blue, item]),
    ppn([the, green, item]),
    ppn([the, red, item]),
    noun([item], [items]),
    tv([bought], [buy]),
    tv([have], [have]),
    tvPrep([bought], [by], [buy], [todooo]),
    tvPrep([knocked], [off], [knock], [todooo])
                     ])).


problem(class_is_in, problem(4, 5, [
        "the math class is either mr. ramon 's or mrs. townsend 's ",
        "the spanish class is n't taught by mr young ",
        "the math class has 6 more students than the spanish class ",
        "of the biology class and the with 25 students one is in room 214 and the other is taught by townsend ",
        "the with 23 students is the algebra class ",
        "the course in room 112 has fewer students than the algebra class ",
        "the with 27 students is n't taught by young ",
        "the statistics class has 6 more students than the in room 228 ",
        "the with 27 students is n't taught by mr hartwood ",
        "neither the math class nor the algebra class is the in room 142 "
                     ], [
    pn([112]),
    pn([134]),
    pn([142]),
    pn([214]),
    pn([228]),
    pn([hartwood]),
    pn([ramon]),
    pn([townsend]),
    pn([young]),
    pn([zellerman]),
    ppn([the, algebra, class]),
    ppn([the, biology, class]),
    ppn([the, math, class]),
    ppn([the, spanish, class]),
    ppn([the, statistics, class]),
    noun([class], [classes]),
    noun([course], [courses]),
    noun([mr], [mrs]),
    noun([room], [rooms]),
    noun([student], [students]),
    tv([has], [have]),
    tv([is], [be]),
    tv([taught], [teach]),
    tvPrep([course], [in], [course], [todooo]),
    tvPrep([is], [in], [be], [todooo]),
    tvPrep([taught], [by], [teach], [todooo])
                     ])).


problem(remodeling_fun, problem(5, 4, [
        "paul and his wife decided that their kitchen needed a serious remodel jack who lived in dallas was n't married to sasha franks last name was n't johnson ",
        "the who decided the den would be the best place to begin lived in detroit ",
        "peter who 's last name was the engle couple married to jenny ",
        "the jackson couple lived in san jose but they did not remodel their dining room ",
        "paul and claudia were not one of the couples the smith couple not have her den remodeled ",
        "the engles had their bathroom remodeled but they did n't own a house in tampa "
                     ], [
    pn([bathroom]),
    pn([claudia]),
    pn([dallas]),
    pn([den]),
    pn([detroit]),
    pn([dining]),
    pn([frank]),
    pn([jack]),
    pn([jenny]),
    pn([kitchen]),
    pn([paul]),
    pn([peter]),
    pn([san]),
    pn([sasha]),
    pn([stephany]),
    pn([tampa]),
    ppn([the, engle, couple]),
    ppn([the, jackson, couple]),
    ppn([the, johnson, couple]),
    ppn([the, smith, couple]),
    noun([couple], [couples]),
    noun([engle], [engles]),
    noun([frank], [franks]),
    noun([house], [houses]),
    noun([jose], [joses]),
    noun([name], [names]),
    noun([place], [places]),
    noun([remodel], [remodels]),
    noun([room], [rooms]),
    noun([wife], [wives]),
    tv([couples], [couple]),
    tv([decided], [decide]),
    tv([had], [have]),
    tv([have], [have]),
    tv([house], [house]),
    tv([lived], [live]),
    tv([married], [marry]),
    tv([remodel], [remodel]),
    tvPrep([decided], [that], [decide], [todooo]),
    tvPrep([house], [in], [house], [todooo]),
    tvPrep([lived], [in], [live], [todooo])
                     ])).


problem(christmas_presents, problem(4, 5, [
        "neither cliff nor jennifer lives in kent ",
        "young crawford asked for the pony ",
        "young rowlands does not live in yorkshire and did not ask for a bicycle ",
        "the gift due for delivery to cornwall is a computer ",
        "the computer is not for the child surnamed rowlands ",
        "liz who has asked for the painting set is not from kent her surname is not jamison ",
        "the child who lives in essex has asked for a guitar ",
        "alan lives in cumbria ",
        "sarah 's surname is not crawford ",
        "jennifer 's surname is feather "
                     ], [
    pn([alan]),
    pn([bicycle]),
    pn([cliff]),
    pn([computer]),
    pn([cornwall]),
    pn([crawford]),
    pn([cumbria]),
    pn([essex]),
    pn([feather]),
    pn([guitar]),
    pn([jamison]),
    pn([jennifer]),
    pn([kent]),
    pn([liz]),
    pn([northey]),
    pn([paint]),
    pn([pony]),
    pn([rowlands]),
    pn([sarah]),
    pn([yorkshire]),
    noun([child], [children]),
    noun([delivery], [deliveries]),
    noun([gift], [gifts]),
    noun([life], [lives]),
    noun([painting], [paintings]),
    noun([set], [sets]),
    noun([surname], [surnames]),
    tv([is], [be]),
    tv([live], [live]),
    tv([lives], [live]),
    tvPrep([ask], [for], [ask], [todooo]),
    tvPrep([asked], [for], [ask], [todooo]),
    tvPrep([live], [in], [live], [todooo]),
    tvPrep([lives], [in], [live], [todooo])
                     ])).


problem(star_students, problem(4, 3, [
        "ms knight who was n't trained as a teacher was an actress in the film magic ",
        "laura is a news anchor ",
        "susan niven never had any ambition to be a nurse ",
        "it is n't the one time student teacher who now presents current affairs programmes "
                     ], [
    pn([actress]),
    pn([donna]),
    pn([knight]),
    pn([lauren]),
    pn([lawyer]),
    pn([news]),
    pn([niven]),
    pn([nurse]),
    pn([presenter]),
    pn([robins]),
    pn([susan]),
    pn([teacher]),
    noun([affair], [affairs]),
    noun([ambition], [ambitions]),
    noun([anchor], [anchors]),
    noun([film], [films]),
    noun([laura], [lauras]),
    noun([m], [ms]),
    noun([magic], [magics]),
    noun([programme], [programmes]),
    noun([student], [students]),
    noun([time], [times]),
    tv([be], [be]),
    tv([is], [be]),
    tv([time], [time]),
    tv([was], [be]),
    tvPrep([trained], [as], [train], [todooo])
                     ])).


problem(baggage_mishaps, problem(4, 3, [
        "the three girls are savannah the american citizen the yellow suitcase and the one traveling to america ",
        "carmelita wants her to stand out so she is not the person with the black suitcase ",
        "of the girl with the yellow suitcase and savannah one is traveling to panama and the other is the american citizen ",
        "gloria is neither the american citizen nor the one going to france and she does not have the black suitcase "
                     ], [
    pn([america]),
    pn([carmelita]),
    pn([france]),
    pn([gloria]),
    pn([panama]),
    pn([savannah]),
    ppn([the, american, citizen]),
    ppn([the, black, suitcase]),
    ppn([the, francen, citizen]),
    ppn([the, green, suitcase]),
    ppn([the, panaman, citizen]),
    ppn([the, yellow, suitcase]),
    noun([citizen], [citizens]),
    noun([girl], [girls]),
    noun([person], [people]),
    noun([suitcase], [suitcases]),
    noun([traveling], [travelings]),
    tv([are], [be]),
    tv([going], [go]),
    tv([have], [have]),
    tv([is], [be]),
    tvPrep([out], [so], [out], [todooo])
                     ])).


problem(planetary_gazing, problem(4, 4, [
        "the person who moved to tampa is not jill ",
        "the friend with the 122000 salary is sally ",
        "the friend who moved to tampa did n't observe saturn or mercury through her telescope ",
        "the friend who moved to houston earns less than her friend in tampa ",
        "the friend with the 95000 salary now lives in los angles ",
        "either the friend living in los angles or the friend who moved to houston caught a great view of jupiter through her telescope ",
        "the friend who 's job is in houston is not jill and she did n't observe saturn through her telescope ",
        "the friend who lives in tampa earns more than the friend who pointed her telescope at jupiter ",
        "the woman living in los angles did n't observe mercury through her telescope and is not jill ",
        "of joann and the amateur astronomer who pointed her telescope at saturn one now lives in houston and the other earns 56000 per year ",
        "the one with the 122000 salary did n't observe mercury through her telescope ",
        "the person living near in tampa is not joann ",
        "the person who found employment in detroit is not becky "
                     ], [
    pn([becky]),
    pn([detroit]),
    pn([houston]),
    pn([jill]),
    pn([joann]),
    pn([jupiter]),
    pn([los]),
    pn([mars]),
    pn([mercury]),
    pn([sally]),
    pn([saturn]),
    pn([tampa]),
    noun([angle], [angles]),
    noun([astronomer], [astronomers]),
    noun([caught], [caughts]),
    noun([employment], [employments]),
    noun([friend], [friends]),
    noun([job], [jobs]),
    noun([living], [livings]),
    noun([one], [ones]),
    noun([person], [people]),
    noun([salary], [salaries]),
    noun([telescope], [telescopes]),
    noun([view], [views]),
    noun([woman], [women]),
    noun([year], [years]),
    tv([earns], [earn]),
    tv([is], [be]),
    tv([lives], [live]),
    tv([living], [live]),
    tv([moved], [move]),
    tv([observe], [observe]),
    tv([telescope], [telescope]),
    tv([view], [view]),
    tvPrep([is], [in], [be], [todooo]),
    tvPrep([lives], [in], [live], [todooo]),
    tvPrep([living], [in], [live], [todooo]),
    tvPrep([living], [near], [live], [todooo]),
    tvPrep([telescope], [at], [telescope], [todooo]),
    tvPrep([view], [of], [view], [todooo])
                     ])).


problem(bart, problem(4, 4, [
        "the 4 people were tatum the patient who was prescribed enalapril the person who earns 54000 and the person who owns the purple house ",
        "of tatum and annabelle one earns 144000 per year and the other lives in the cyan house ",
        "the patient who was prescribed enalapril is not heather ",
        "either the employee who earns 144000 or the employee who earns 158000 lives in the blue house ",
        "kassidy earns less than heather ",
        "the owner of the blue house earns more than kassidy ",
        "the patient who was prescribed ramipril is not annabelle ",
        "the owner of the lime house was prescribed enalapril for their heart condition ",
        "the employee who earns 144000 was prescribed benazepril for their heart condition "
                     ], [
    pn([annabelle]),
    pn([benazepril]),
    pn([enalapril]),
    pn([fosinopril]),
    pn([heather]),
    pn([kassidy]),
    pn([ramipril]),
    pn([tatum]),
    ppn([the, blue, house]),
    ppn([the, cyan, house]),
    ppn([the, lime, house]),
    ppn([the, purple, house]),
    noun([condition], [conditions]),
    noun([employee], [employees]),
    noun([heart], [hearts]),
    noun([house], [houses]),
    noun([life], [lives]),
    noun([owner], [owners]),
    noun([patient], [patients]),
    noun([person], [people]),
    noun([year], [years]),
    tv([earns], [earn]),
    tv([is], [be]),
    tv([owns], [own]),
    tv([people], [people]),
    tvPrep([lives], [in], [live], [todooo]),
    tvGap([was, prescribed], [for, their, heart, condition], [prescribe])
                     ])).


problem(be_my_valentine, problem(4, 3, [
        "unluckily for freddie when miss jetson received her she thought it was from adam ",
        "when molly received a blue card she told miss hanson and together they worked out who the was from it did n't occur to either of them that it was from freddie ",
        "the girl who received the red was convinced it came from ethan ",
        "neither millie nor miss motson received a pink card "
                     ], [
    pn([]),
    pn([dylan]),
    pn([ethan]),
    pn([hanson]),
    pn([jetson]),
    pn([lily]),
    pn([millie]),
    pn([molly]),
    pn([motson]),
    ppn([a,  red, card]),
    ppn([a, blue, card]),
    ppn([a, pink, card]),
    noun([adam], [adams]),
    noun([card], [cards]),
    noun([freddie], [freddies]),
    noun([girl], [girls]),
    noun([miss], [misses]),
    tv([came], [come]),
    tv([miss], [miss]),
    tv([received], [receive]),
    tv([told], [tell]),
    tvPrep([came], [from], [come], [todooo]),
    tvPrep([was], [from], [be], [todooo])
                     ])).


problem(dragon_slayer, problem(4, 5, [
        "both sir percival and the knight who slew the welsh dragon had green in their colors ",
        "the knight that battled the ancient dragon wore colors of blue white ",
        "neither sir dane or sir richard had green in their colors ",
        "sir gwain fought the irish dragon ",
        "the knight that slew the ancient dragon bore the shield ",
        "the knights that carried an axe and a sword both had white in their colors ",
        "an arrow from the bow pierced the english dragon ",
        "one of the knights who had green in their colors carried the bow ",
        "both sir richard and sir gwain had red in their colors ",
        "the irish dragon was slain with a sword "
                     ], [
    pn([axe]),
    pn([blue]),
    pn([bow]),
    pn([green]),
    pn([mace]),
    pn([red]),
    pn([shield]),
    pn([sir]),
    pn([sword]),
    ppn([the, ancient, dragon]),
    ppn([the, english, dragon]),
    ppn([the, irish, dragon]),
    ppn([the, scottish, dragon]),
    ppn([the, welsh, dragon]),
    noun([arrow], [arrows]),
    noun([color], [colors]),
    noun([dane], [danes]),
    noun([dragon], [dragons]),
    noun([gwain], [gwains]),
    noun([knight], [knights]),
    noun([percival], [percivals]),
    noun([richard], [richards]),
    tv([battled], [battle]),
    tv([bore], [bore]),
    tv([carried], [carry]),
    tv([fought], [fight]),
    tv([had], [have]),
    tvPrep([colors], [of], [color], [todooo]),
    tvPrep([green], [in], [green], [todooo])
                     ])).


problem(kids_at_play, problem(4, 3, [
        "tommy was always upset to be called in for dinner before the other 2 boys ",
        "the jones boy had dinner ready later than 600pm ",
        "of dickey and the jackson boy one loved playing red light green light and the other 's dinner was at 600pm sharp ",
        "the jackson boy did n't like hide and seek as much as tommy ",
        "harry always had 15 alone once the others were called in ",
        "the smith boy have 15 minutes to read the newspaper after work before dinner was on the table at 530pm ",
        "the jones boy playing tag "
                     ], [
    pn([530]),
    pn([600]),
    pn([615]),
    pn([dickey]),
    pn([harry]),
    pn([hide/seek]),
    pn([red]),
    pn([tag]),
    pn([tommy]),
    ppn([the, jackson, boy]),
    ppn([the, jones, boy]),
    ppn([the, smith, boy]),
    noun([boy], [boys]),
    noun([dinner], [dinners]),
    noun([hide], [hides]),
    noun([light], [lights]),
    noun([minute], [minutes]),
    noun([newspaper], [newspapers]),
    noun([other], [others]),
    noun([playing], [playings]),
    noun([table], [tables]),
    noun([work], [works]),
    tv([had], [have]),
    tv([have], [have]),
    tv([loved], [love]),
    tvPrep([called], [in], [call], [todooo]),
    tvPrep([table], [at], [table], [todooo]),
    tvPrep([was], [at], [be], [todooo]),
    tvPrep([was], [on], [be], [todooo]),
    tvPrep([work], [before], [work], [todooo])
                     ])).


problem(classroom_blues, problem(4, 3, [
        "the student being moved farthest from the front of the classroom gets in trouble for throwing airplanes ",
        "mr. williams taught his son how to build paper airplanes ",
        "gloria has a hard time staying awake in class ",
        "raymond pierce is being moved closest to the door "
                     ], [
    pn([back]),
    pn([front]),
    pn([gloria]),
    pn([michael]),
    pn([near]),
    pn([pierce]),
    pn([raymond]),
    pn([sharp]),
    pn([sleeping]),
    pn([talking]),
    pn([throwing]),
    pn([williams]),
    noun([airplane], [airplanes]),
    noun([awake], [awakes]),
    noun([class], [classes]),
    noun([classroom], [classrooms]),
    noun([door], [doors]),
    noun([paper], [papers]),
    noun([son], [sons]),
    noun([student], [students]),
    noun([time], [times]),
    noun([trouble], [troubles]),
    tv([trouble], [trouble]),
    tvPrep([front], [of], [front], [todooo]),
    tvPrep([gets], [in], [get], [todooo]),
    tvPrep([trouble], [for], [trouble], [todooo])
                     ])).


problem(trick_or_treating, problem(5, 4, [
        "of the 4 children there was the 8 year old the child who dressed as a werewolf the child who was accompanied by their sister and the one who carried a red flashlight ",
        "between the 9 year old and frank who is older than toby one was dressed as a goblin and the other carried a green flashlight ",
        "neither frank nor judy were accompanied by their sister while trick or treating judy did not carry a orange flashlight ",
        "toby 's mother was upset that he cut up one of her favorite sheets to create his ghost costume ",
        "the child who dressed as a werewolf was accompanied by a male and did not carry a green flashlight ",
        "the nine year old was quite happy with her goblin costume which she spent an entire week designing ",
        "either frank or toby carried a green flashlight ",
        "the child who was accompanied by their brother was exactly 2 years older than the child who went with their sister ",
        "jessica caught her uncle sneaking candy from her bag while they walked ",
        "the child dressed as a ghost carried a blue flashlight "
                     ], [
    pn([aunt]),
    pn([brother]),
    pn([frank]),
    pn([ghost]),
    pn([goblin]),
    pn([jessica]),
    pn([judy]),
    pn([sister]),
    pn([toby]),
    pn([uncle]),
    pn([vampire]),
    pn([werewolf]),
    ppn([a, blue, flashlight]),
    ppn([a, green, flashlight]),
    ppn([a, orange, flashlight]),
    ppn([a, red, flashlight]),
    noun([bag], [bags]),
    noun([candy], [candies]),
    noun([child], [children]),
    noun([costume], [costumes]),
    noun([designing], [designings]),
    noun([flashlight], [flashlights]),
    noun([male], [males]),
    noun([mother], [mothers]),
    noun([one], [ones]),
    noun([sheet], [sheets]),
    noun([trick], [tricks]),
    noun([week], [weeks]),
    noun([year], [years]),
    tv([carried], [carry]),
    tv([carry], [carry]),
    tv([caught], [catch]),
    tv([create], [create]),
    tv([frank], [frank]),
    tv([treating], [treat]),
    tvPrep([accompanied], [by], [accompany], [todooo]),
    tvPrep([bag], [while], [bag], [todooo]),
    tvPrep([dressed], [as], [dress], [todooo]),
    tvPrep([upset], [that], [upset], [todooo]),
    tvPrep([went], [with], [go], [todooo])
                     ])).


problem(greek_dogs, problem(4, 5, [
        "the 5 people were jenny the person married in 1929 the person with the att cell phone the person who named their dog cassiopeia and julie ",
        "the person with the sprint cell phone got married after the person who named their dog agamemnon ",
        "the person who named their dog hephaestus got married before the person who named their dog agamemnon ",
        "the person who named their dog cassiopeia got married after the person with the tmobile cell phone ",
        "the person with the att cell phone is not jason ",
        "the person married in 1976 is james ",
        "of the person with the sprint cell phone and jason one got married in 1946 and the other named their dog agamemnon ",
        "the person married in 1982 named their dog lycurgus ",
        "the person who named their dog lycurgus is not josie or jenny ",
        "either the person with the nextel cell phone or the person with the sprint cell phone is james "
                     ], [
    pn([agamemnon]),
    pn([cassiopeia]),
    pn([endymion]),
    pn([hephaestus]),
    pn([james]),
    pn([jason]),
    pn([jenny]),
    pn([josie]),
    pn([julie]),
    pn([lycurgus]),
    ppn([the, att, cell]),
    ppn([the, nextel, cell]),
    ppn([the, sprint, cell]),
    ppn([the, tmobile, cell]),
    ppn([the, verizon, cell]),
    noun([cell], [cells]),
    noun([dog], [dogs]),
    noun([person], [people]),
    noun([phone], [phones]),
    tv([is], [be]),
    tv([people], [people]),
    tvPrep([married], [after], [marry], [todooo]),
    tvPrep([married], [before], [marry], [todooo]),
    tvPrep([married], [in], [marry], [todooo])
                     ])).


problem(time_to_quit, problem(4, 5, [
        "the people subscriber the person who grows kiwis the employee whose last day will be july 8 the people subscriber trenton and the person who grows guavas ",
        "the time subscriber will leave before the newsweek subscriber ",
        "the time subscriber does n't grow guavas ",
        "the time subscriber will leave before ricky ",
        "of trenton and the person who grows apples one is leaving the company on september 23 and the other subscribed to usweekly ",
        "the person who grows boysenberries is trenton ",
        "bianca will leave after roger ",
        "the newsweek subscriber is not ricky ",
        "the person who grows kiwis is not roger ",
        "either the employee whose last day will be january 13 or the employee whose last day will be september 23 grows strawberries ",
        "the usweekly subscriber is bianca "
                     ], [
    pn([apples]),
    pn([august]),
    pn([bianca]),
    pn([boysenberries]),
    pn([charlie]),
    pn([guavas]),
    pn([january]),
    pn([july]),
    pn([kiwis]),
    pn([may]),
    pn([ricky]),
    pn([roger]),
    pn([september]),
    pn([strawberries]),
    pn([trenton]),
    ppn([the, fortune, subscriber]),
    ppn([the, newsweek, subscriber]),
    ppn([the, people, subscriber]),
    ppn([the, time, subscriber]),
    ppn([the, usweekly, subscriber]),
    noun([company], [companies]),
    noun([day], [days]),
    noun([employee], [employees]),
    noun([grow], [grows]),
    noun([person], [people]),
    noun([subscriber], [subscribers]),
    tv([company], [company]),
    tv([grows], [grow]),
    tv([is], [be]),
    tv([people], [people]),
    tv([subscribed], [subscribe]),
    tv([will], [will]),
    tvPrep([company], [on], [company], [todooo]),
    tvPrep([leave], [after], [leave], [todooo]),
    tvPrep([leave], [before], [leave], [todooo])
                     ])).


problem(breakfast_time, problem(4, 3, [
        "the person who read the newspaper had breakfast later than the person who liked to listen to the news on the radio ",
        "jennifer had her breakfast directly before the person who had toast ",
        "cereal was eaten 20 minutes after the person who watched the breakfast news on tv ",
        "claudia 's black coffee was not the breakfast taken last "
                     ], [
    pn([630]),
    pn([650]),
    pn([715]),
    pn([cereal]),
    pn([claudia]),
    pn([coffee]),
    pn([jennifer]),
    pn([newspaper]),
    pn([radio]),
    pn([steph]),
    pn([television]),
    pn([toast]),
    noun([breakfast], [breakfasts]),
    noun([minute], [minutes]),
    noun([news], [news]),
    noun([person], [people]),
    noun([tv], [tvs]),
    tv([read], [read])
                     ])).


problem(piracy, problem(4, 3, [
        "the saucy sue is not the ship of the buccaneer who lost his left hand and who spent 4 years living on coconut milk and fish ",
        "the buccaneer with only one eye spent the longest time marooned but was not captain stump ",
        "mean mike lost a leg after a cutlass wound went septic ",
        "grey beard 's ship is called big bess "
                     ], [
    pn([big]),
    pn([captain]),
    pn([eye]),
    pn([grey]),
    pn([hand]),
    pn([leg]),
    pn([mean]),
    pn([merry]),
    pn([suacy]),
    noun([beard], [beards]),
    noun([bess], [besses]),
    noun([buccaneer], [buccaneers]),
    noun([coconut], [coconuts]),
    noun([cutlass], [cutlasses]),
    noun([fish], [fish]),
    noun([mike], [mikes]),
    noun([milk], [milks]),
    noun([saucy], [saucies]),
    noun([ship], [ships]),
    noun([stump], [stumps]),
    noun([sue], [sues]),
    noun([time], [times]),
    noun([wound], [wounds]),
    noun([year], [years]),
    tv([lost], [lose]),
    tv([spent], [spend]),
    tv([was], [be]),
    tvPrep([buccaneer], [with], [buccaneer], [todooo]),
    tvPrep([living], [on], [live], [todooo]),
    tvPrep([ship], [of], [ship], [todooo])
                     ])).


problem(breakfast_at_tiffanys, problem(4, 4, [
        "samantha had a bowl of cereal but not a latte ",
        "the friend who ordered the potato pancakes also ordered a coffee to go but did n't have an ice tea ",
        "the woman who ordered the omelet had apple juice to drink but she was n't jenny ",
        "of the two friends who ordered the orange juice and the ice tea one was jackie and the other was the friend who ordered the french toast ",
        "the friend who ordered a bottle of water to go did n't order orange juice ",
        "judy ordered a lemonade to go "
                     ], [
    pn([apple]),
    pn([cereal]),
    pn([chocolate]),
    pn([coffee]),
    pn([french]),
    pn([ice]),
    pn([jackie]),
    pn([jenny]),
    pn([judy]),
    pn([latte]),
    pn([lemonade]),
    pn([omlet]),
    pn([orange]),
    pn([pancakes]),
    pn([samantha]),
    pn([water]),
    noun([bottle], [bottles]),
    noun([bowl], [bowls]),
    noun([friend], [friends]),
    noun([juice], [juices]),
    noun([omelet], [omelets]),
    noun([order], [orders]),
    noun([potato], [potatoes]),
    noun([tea], [teas]),
    noun([toast], [toasts]),
    noun([woman], [women]),
    tv([bottle], [bottle]),
    tv([bowl], [bowl]),
    tv([had], [have]),
    tv([have], [have]),
    tv([order], [order]),
    tv([ordered], [order]),
    tv([was], [be]),
    tvPrep([bottle], [of], [bottle], [todooo]),
    tvPrep([bowl], [of], [bowl], [todooo])
                     ])).


problem(beach_bum, problem(4, 4, [
        "alexandra found a lovely sharks tooth 3 years after the souvenir she bought on topsail island ",
        "the conch shell was n't found in 2007 ",
        "of the souvenir she purchased in 2013 and the one she bought in longbeach one is the sharks tooth and the other was purchased at saltys marina ",
        "she simply could n't resist the hula girl that swayed back and forth that she saw either while she was in santa barbara or while staying on topsail island ",
        "while on southpadre island she either purchased the hula girl or visited island gifts ",
        "she either purchased the pearl bracelet in 2004 or while she was browsing at ocean treasures ",
        "neither the souvenir purchased while on southpadre island nor the conch shell is the souvenir found in 2004 ",
        "the souvenir she found while on topsail island was n't from ocean treasures "
                     ], [
    pn([beach]),
    pn([conch]),
    pn([hula]),
    pn([island]),
    pn([longbeach]),
    pn([ocean]),
    pn([pearl]),
    pn([saltys]),
    pn([santabarbara]),
    pn([sharks]),
    pn([southpadre]),
    pn([topsail]),
    noun([alexandra], [alexandras]),
    noun([barbara], [barbaras]),
    noun([bracelet], [bracelets]),
    noun([forth], [forths]),
    noun([gift], [gifts]),
    noun([girl], [girls]),
    noun([marina], [marinas]),
    noun([shell], [shells]),
    noun([souvenir], [souvenirs]),
    noun([treasure], [treasures]),
    noun([year], [years]),
    tv([bought], [buy]),
    tv([is], [be]),
    tv([resist], [resist]),
    tv([staying], [stay]),
    tv([visited], [visit]),
    tvPrep([bought], [in], [buy], [todooo]),
    tvPrep([bought], [on], [buy], [todooo]),
    tvPrep([browsing], [at], [browse], [todooo]),
    tvPrep([found], [in], [find], [todooo]),
    tvPrep([found], [while], [find], [todooo]),
    tvPrep([staying], [on], [stay], [todooo]),
    tvPrep([was], [in], [be], [todooo])
                     ])).


problem(pet_or_no_pet, problem(4, 3, [
        "neither girl lives in the odd-numbered house ",
        "the spaniel does not live at number 24 nor with sammy ",
        "sarah who is not the oldest lives furthest from number 15 ",
        "the girl whose age and house number match does not have a pet "
                     ], [
    pn([no]),
    pn([sally]),
    pn([sammy]),
    pn([sarah]),
    pn([spaniel]),
    pn([terrier]),
    noun([age], [ages]),
    noun([girl], [girls]),
    noun([house], [houses]),
    noun([life], [lives]),
    noun([match], [matches]),
    noun([number], [numbers]),
    noun([pet], [pets]),
    tv([number], [number]),
    tvPrep([live], [at], [live], [todooo]),
    tvPrep([lives], [in], [live], [todooo])
                     ])).


% cookies_for_love, expensive_homes, at_the_farm, tutorial, new_shoes, cats_in_spring, a_bargain, class_is_in, remodeling_fun, christmas_presents, star_students, baggage_mishaps, planetary_gazing, bart, be_my_valentine, dragon_slayer, kids_at_play, classroom_blues, trick_or_treating, greek_dogs, time_to_quit, breakfast_time, piracy, breakfast_at_tiffanys, beach_bum, pet_or_no_pet
