
:- module(problemHolyGrail, [problem/2]).

problem(tutorial, problem(4, 4, [
        % "The 4 people were Tatum, the patient who was prescribed enalapril, the employee with the $54,000 salary, and the owner of the purple house",
% CHANGED TO: ( "with the salary")
        "The 4 people were tatum, the patient who was prescribed enalapril, the employee who earns 54000, and the owner of the purple house",
        "The patient who was prescribed enalapril is not heather",
        "The patient who was prescribed ramipril is not annabelle",
        "kassidy earns less than heather",
        "The owner of the blue house earns more than kassidy",
%%    "Of tatum and annabelle, one earns 144000 per year and the other lives in the cyan colored house",
%% CHANGED TO: (drop: colored)
        "Of tatum and annabelle, one earns 144000 per year and the other lives in the cyan house",
%%        "Either the employee with the 144000 salary or the employee with the 158000 salary lives in the blue colored house",
%% CHANGED TO: (drop colored, change the ...salara) 
        "Either the employee who earns 144000  or the employee who earns 158000 lives in the blue house",
        "The owner of the lime house was prescribed enalapril for their heart condition",
%%        "The employee with the 144000 salary was prescribed benazepril for their heart condition"
%% CHANGED TO:
        "The employee who earns 144000 was prescribed benazepril for their heart condition"
                     ], [
                        noun([patient], [patients]),
                        noun([person], [people]),
                        noun([year], [years]),
                        noun([employee], [employees]),
                        noun([salary], [salaries]),
                        noun([owner], [owners]),
                        pn([tatum]),
                        pn([annabelle]),
                        pn([heather]),
                        pn([kassidy]),
                        pn([benazepril]),
                        pn([enalapril]),
                        pn([ramipril]),
                        pn([fosinopril]),
                        prep([of]),
                        ppn([the, blue, house]),
                        ppn([the, lime, house]),
                        ppn([the, cyan, house]),
                        ppn([the, purple, house]),
                        tv([owns], [own]),
                        tvGap([earns], [per, year], [earn]),
                        tvGap([was, prescribed], [for, their, heart, condition], [prescribe]),
                        tvPrep([lives], [in], [live], [lived])
                     ])).

problem(p2_types, problem(4,5, [
                        "Of the contestant who scored 41 points and the person who threw the white darts, one was from Worthington and the other was Ira",
                        "Bill was from Mount union",
                        "Ira scored 21 points higher than the contestant from Worthington",
                        "Oscar scored somewhat higher than the player who threw the orange darts",
                        "The contestant from Mount union threw the black darts",
                        "Pedro didn't finish with 55 points",
                        "The player who threw the red darts was either Colin or the contestant who scored 48 points",
                        "Of the contestant who scored 41 points and the person who threw the orange darts, one was from Gillbertville and the other was from Worthington",
                        "Ira scored 7 points lower than the player from Lohrville"
        ], [
                        noun([contestant], [contestants]),
                        noun([person], [persons]),
                        noun([player], [players]),
                        noun([point], [points]),
                        pn([bill], A),
                        pn([colin], A),
                        pn([ira], A),
                        pn([oscar], A),
                        pn([pedro], A),
                        pn([mount, union], B),
                        pn([gillbertville], B),
                        pn([lohrville], B),
                        pn([worthington], B),
                        pn([yorktown], B),
                        ppn([the, black, darts], C),
                        ppn([the, orange, darts], C),
                        ppn([the, red, darts], C),
                        ppn([the, white, darts], C),
                        ppn([the, yellow, darts], C),
                        tv([threw], [throw]),
                        tv([scored], [score]),
                        tvPrep([finishes], [with], [finish], [finished]),
                        prep([from])
        ])).
    
problem(cookies_for_love, problem(5, 4, [
        "jackie 's last name was not fredericks . the cookies sold at bake sale were to help the cook family . ",
        "the ginger snap cookies were not baked to help the hatfield family . june , whose last name was not baker , sponsored the adams family . ",
        "ms smith , whose first name was not joyce , made the chocolate chip cookies but she did not sponsor the cook family . ",
        "judy levinson did not sell her cookies at the bake sale . the ginger snaps were not baked by the woman sponsoring the adams family ",
        "the peanut butter cookies were banked to help the van wert family , but they were not sold at the pot luck . ",
        "joyce sold her cookies at the school play . the sugar cookies were sold before and after sunday church . "
                     ], [
    pn([adams]),
    pn([bake, sale]),
    pn([baker]),
    pn([chocolate, chip]),
    pn([church]),
    pn([cook]),
    pn([fredericks]),
    pn([ginger, snaps]),
    pn([hatfield]),
    pn([jackie]),
    pn([joyce]),
    pn([judy]),
    pn([june]),
    pn([levinson]),
    pn([peanut, butter]),
    pn([pot, luck]),
    pn([school, play]),
    pn([smith]),
    pn([sugar]),
    pn([van, wert]),
    noun([cookies], [cookies]),
    noun([family], [families]),
    noun([ms], [mss]),
    noun([name], [names]),
    noun([woman], [women]),
    tv([made], [make]),
    tv([were], [be]),
    tv([were, banked], [be]),
    tv([sponsor], [sponsor]),
    tv([was], [be]),
    tv([were, sold], [be]),
    tv([sponsoring], [sponsor]),
    tv([sponsored], [sponsor]),
    tv([help], [help]),
    tvPrep([baked], [by], [bake], [todooo]),
    tvPrep([sold], [at], [sell], [todooo])
                     ])).


problem(expensive_homes, problem(4, 3, [
        "kassandra 's home is worth more than that of the person whose last name is holloway . ",
        "the elm tree road resident owns the least valued home . ",
        "alexandra lives in neither treelined boulevard nor elm tree road but in the most valued home . ",
        "holt is not the last name of the wattle grove resident . "
                     ], [
    pn([alexandra]),
    pn([angelo]),
    pn([elm, tree, road]),
    pn([holloway]),
    pn([holt]),
    pn([kassandra]),
    pn([melton]),
    pn([treelined, boulevard]),
    pn([wattle, grove]),
    noun([home], [homes]),
    noun([life], [lives]),
    noun([name], [names]),
    noun([person], [people]),
    noun([resident], [residents]),
    tv([home], [home]),
    tv([valued], [value]),
    tv([tree], [tree]),
    tv([owns], [own]),
    tvPrep([is], [worth], [be], [todooo]),
    tvPrep([lives], [in], [live], [todooo])
                     ])).


problem(at_the_farm, problem(4, 5, [
        "fran 's day to mend fences is neither tuesday nor thursday , and is completed earlier in the week than at least one other person . ",
        "the one who goes to market goes later in the week than carl , and earlier in the morning than nan , but later in the morning than fran . ",
        "adam does not plant the corn , or go to market , his chore is completed before 9am , but not before 6am on his assigned day of monday . ",
        "no one performs a chore on thursday at 7am . ",
        "mike 's chore is completed earlier in the day than at least 3 others , but later in the week than at least three others . ",
        "one of the boys collects eggs , another boy milks bessie , the goat . ",
        "the milk is collected earlier in the week than the girl who plants the corn , which is not planted before wednesday . ",
        "the eggs must be collected at 7 am , but never on mondays or fridays . ",
        "all the other chores must be complete before mike goes to the market . "
                     ], [
    pn([adam]),
    pn([carl]),
    pn([corn]),
    pn([eggs]),
    pn([fran]),
    pn([friday]),
    pn([market]),
    pn([mend]),
    pn([mike]),
    pn([milk]),
    pn([monday]),
    pn([nan]),
    pn([thursday]),
    pn([tuesday]),
    pn([wednesday]),
    noun([am], [ams]),
    noun([boy], [boys]),
    noun([chore], [chores]),
    noun([day], [days]),
    noun([fence], [fences]),
    noun([friday], [fridays]),
    noun([girl], [girls]),
    noun([goat], [goats]),
    noun([milk], [milks]),
    noun([monday], [mondays]),
    noun([morning], [mornings]),
    noun([one], [ones]),
    noun([other], [others]),
    noun([person], [people]),
    noun([plant], [plants]),
    noun([week], [weeks]),
    tv([is, collected], [be]),
    tv([bessie], [bessie]),
    tv([is], [be]),
    tv([goes], [go]),
    tv([performs], [perform]),
    tv([is, completed], [be]),
    tv([go], [go]),
    tv([be, collected], [be]),
    tv([be], [be]),
    tvPrep([collected], [at], [collect], [todooo]),
    tvPrep([completed], [before], [complete], [todooo]),
    tvPrep([planted], [before], [plant], [todooo])
                     ])).


problem(tutorial, problem(4, 4, [
        "the 4 people were tatum , the patient who was prescribed enalapril , the employee with the $ 54000 salary , and the owner of the purple house . ",
        "of tatum and annabelle , one earns $ 144000 per year and the other lives in the cyan colored house . ",
        "the patient who was prescribed enalapril is not heather . ",
        "either the employee with the $ 144000 salary or the employee with the $ 158000 salary lives in the blue colored house . ",
        "kassidy earns less than heather . ",
        "the owner of the blue house earns more than kassidy . ",
        "the patient who was prescribed ramipril is not annabelle . ",
        "the owner of the lime house was prescribed enalapril for their heart condition . ",
        "the employee with the $ 144000 salary was prescribed benazepril for their heart condition . "
                     ], [
    pn([annabelle]),
    pn([benazepril]),
    pn([blue]),
    pn([cyan]),
    pn([enalapril]),
    pn([fosinopril]),
    pn([heather]),
    pn([kassidy]),
    pn([lime]),
    pn([purple]),
    pn([ramipril]),
    pn([tatum]),
    noun([condition], [conditions]),
    noun([employee], [employees]),
    noun([heart], [hearts]),
    noun([house], [houses]),
    noun([life], [lives]),
    noun([owner], [owners]),
    noun([patient], [patients]),
    noun([person], [people]),
    noun([salary], [salaries]),
    noun([year], [years]),
    tv([earns], [earn]),
    tv([is], [be]),
    tv([was, prescribed], [be]),
    tv([colored], [colore]),
    tv([were], [be])
                     ])).


problem(new_shoes, problem(4, 3, [
        "the pumps were not pink . ",
        "the boots were brown but were not purchased by margaret . ",
        "clarisse did not buy the pumps but spent more than sally . ",
        "margaret got the sandals , which cost twice as much as sally 's purchase , but were not green . "
                     ], [
    pn([boots]),
    pn([brown]),
    pn([clarisse]),
    pn([green]),
    pn([margaret]),
    pn([pink]),
    pn([pumps]),
    pn([sally]),
    pn([sandals]),
    noun([cost], [costs]),
    noun([purchase], [purchases]),
    tv([were], [be]),
    tv([spent], [spend]),
    tv([buy], [buy]),
    tv([got], [get]),
    tvPrep([purchased], [by], [purchase], [todooo])
                     ])).


problem(cats_in_spring, problem(4, 3, [
        "batman chose the female who liked to chase a ball , but she was not starbuck . ",
        "dibii 's companion liked to chase the laser light . ",
        "ruby loved to cuddle up to her male for a long afternoon nap in the sun . ",
        "starbuck had two more kittens than batman 's companion . "
                     ], [
    pn([ball]),
    pn([batman]),
    pn([dibii]),
    pn([jake]),
    pn([lazer]),
    pn([ruby]),
    pn([sleep]),
    pn([spot]),
    pn([starbuck]),
    noun([afternoon], [afternoons]),
    noun([companion], [companions]),
    noun([female], [females]),
    noun([kitten], [kittens]),
    noun([laser], [lasers]),
    noun([light], [lights]),
    noun([male], [males]),
    noun([nap], [naps]),
    noun([sun], [suns]),
    tv([cuddle], [cuddle]),
    tv([liked], [like]),
    tv([chose], [choose]),
    tv([chase], [chase]),
    tv([loved], [love]),
    tv([was], [be])
                     ])).


problem(a_bargain, problem(4, 3, [
        "the blue jacket was not bought by benny . ",
        "daniella was pleased to have $ 900 knocked off the item she bought . ",
        "the red item had more knocked off than the umbrella . ",
        "the trousers did not have $ 500 knocked off and were not bought by benny or carla . "
                     ], [
    pn([benny]),
    pn([blue]),
    pn([carla]),
    pn([daniella]),
    pn([green]),
    pn([jacket]),
    pn([red]),
    pn([trousers]),
    pn([umbrella]),
    noun([item], [items]),
    tv([were], [be]),
    tv([was], [be]),
    tvPrep([bought], [by], [buy], [todooo]),
    tvPrep([knocked], [off], [knock], [todooo])
                     ])).


problem(class_is_in, problem(4, 5, [
        "the math class is either mr ramon 's class or mrs townsend 's class . ",
        "the spanish class is not taught by mr young . ",
        "the math class has 6 more students than the spanish class . ",
        "of the biology class and the class with 25 students , one is in room 214 and the other is taught by townsend . ",
        "the class with 23 students is the algebra class . ",
        "the course in room 112 has fewer students than the algebra class . ",
        "the class with 27 students is not taught by young . ",
        "the statistics class has 6 more students than the class in room 228 . ",
        "the class with 27 students is not taught by mr hartwood . ",
        "neither the math class nor the algebra class is the class in room 142 . "
                     ], [
    pn([112]),
    pn([134]),
    pn([142]),
    pn([214]),
    pn([228]),
    pn([algebra]),
    pn([biology]),
    pn([hartwood]),
    pn([math]),
    pn([ramon]),
    pn([spanish]),
    pn([statistics]),
    pn([townsend]),
    pn([young]),
    pn([zellerman]),
    noun([class], [classes]),
    noun([course], [courses]),
    noun([mr], [mrs]),
    noun([room], [rooms]),
    noun([student], [students]),
    tv([mrs], [mr]),
    tvPrep([is], [in], [be], [todooo]),
    tvPrep([taught], [by], [teach], [todooo])
                     ])).


problem(remodeling_fun, problem(5, 4, [
        "paul and his wife decided that their kitchen needed a serious remodel . jack , who lived in dallas , was not married to sasha . franks last name was not johnson . ",
        "the couple who decided the den would be the best place to begin lived in detroit . ",
        "peter , who 's last name was not engle , was married to jenny ",
        "the jackson couple lived in san jose , but they did not remodel their dining room . ",
        "paul and claudia were not one of the couples . stephany smith did not have her den remodeled . ",
        "the engles had their bathroom remodeled , but they did not own a house in tampa . "
                     ], [
    pn([bathroom]),
    pn([claudia]),
    pn([dallas]),
    pn([den]),
    pn([detroit]),
    pn([dining, room]),
    pn([engle]),
    pn([frank]),
    pn([jack]),
    pn([jackson]),
    pn([jenny]),
    pn([johnson]),
    pn([kitchen]),
    pn([paul]),
    pn([peter]),
    pn([san, jose]),
    pn([sasha]),
    pn([smith]),
    pn([stephany]),
    pn([tampa]),
    noun([couple], [couples]),
    noun([engle], [engles]),
    noun([frank], [franks]),
    noun([house], [houses]),
    noun([name], [names]),
    noun([place], [places]),
    noun([remodel], [remodels]),
    noun([wife], [wives]),
    tv([begin, lived], [begin]),
    tv([were], [be]),
    tv([was, married], [be]),
    tv([remodeled], [remodel]),
    tv([needed], [need]),
    tv([own], [own]),
    tv([was], [be]),
    tv([remodel], [remodel]),
    tv([married], [marry]),
    tv([be], [be]),
    tvPrep([decided], [that], [decide], [todooo]),
    tvPrep([lived], [in], [live], [todooo])
                     ])).


problem(christmas_presents, problem(4, 5, [
        "neither cliff nor jennifer lives in kent . ",
        "young crawford asked for the pony . ",
        "young rowlands does not live in yorkshire and did not ask for a bicycle . ",
        "the gift due for delivery to cornwall is a computer . ",
        "the computer is not for the child surnamed rowlands . ",
        "liz , who has asked for the painting set , is not from kent . her surname is not jamison . ",
        "the child who lives in essex has asked for a guitar . ",
        "alan lives in cumbria . ",
        "sarah 's surname is not crawford . ",
        "jennifer 's surname is feather . "
                     ], [
    pn([alan]),
    pn([bicycle]),
    pn([cliff]),
    pn([computer]),
    pn([cornwall]),
    pn([crawford]),
    pn([cumbria]),
    pn([essex]),
    pn([feather]),
    pn([guitar]),
    pn([jamison]),
    pn([jennifer]),
    pn([kent]),
    pn([liz]),
    pn([northey]),
    pn([paint, set]),
    pn([pony]),
    pn([rowlands]),
    pn([sarah]),
    pn([yorkshire]),
    noun([child], [children]),
    noun([delivery], [deliveries]),
    noun([gift], [gifts]),
    noun([life], [lives]),
    noun([painting], [paintings]),
    noun([surname], [surnames]),
    tv([is], [be]),
    tv([surnamed], [surname]),
    tvPrep([asked], [for], [ask], [todooo]),
    tvPrep([lives], [in], [live], [todooo])
                     ])).


problem(p1_json, problem(4, 5, [
        "the perens pig lives in slovakia and was recognized as endangered in 2009 ",
        "the eldar elk has a population size of 210 ",
        "the byengo bat does not live in ghana ",
        "the animal that lives in slovakia was listed sometime before the animal from russia ",
        "of the species with a population size of 490 and the eldar elk , one lives in poland and the other was recognized as endangered in 2009 ",
        "neither the nibner newt nor the byengo bat has a surviving population size of 525 ",
        "the species that lives in ghana was listed 2 years after the nibner newt ",
        "the animal that lives in russia does not have a surviving population size of 315 "
                     ], [
    pn([byengo, bat]),
    pn([eldar, elk]),
    pn([ghana]),
    pn([honduras]),
    pn([nibner, newt]),
    pn([osbele, oryx]),
    pn([perens, pig]),
    pn([poland]),
    pn([russia]),
    pn([slovakia]),
    noun([animal], [animals]),
    noun([life], [lives]),
    noun([population], [populations]),
    noun([size], [sizes]),
    noun([species], [species]),
    noun([year], [years]),
    tv([surviving], [survive]),
    tv([was, recognized], [be]),
    tv([was, listed], [be]),
    tvPrep([endangered], [in], [endanger], [todooo]),
    tvPrep([lives], [in], [live], [todooo]),
    tvPrep([recognized], [as], [recognize], [todooo])
                     ])).


problem(star_students, problem(4, 3, [
        "ms knight , who was not trained as a teacher , was an actress in the film magic . ",
        "laura is a news anchor . ",
        "susan niven never had any ambition to be a nurse . ",
        "it is not the one time student teacher who now presents current affairs programmes . "
                     ], [
    pn([actress]),
    pn([donna]),
    pn([knight]),
    pn([lauren]),
    pn([lawyer]),
    pn([news, anchor]),
    pn([niven]),
    pn([nurse]),
    pn([presenter]),
    pn([robins]),
    pn([susan]),
    pn([teacher]),
    noun([affair], [affairs]),
    noun([ambition], [ambitions]),
    noun([film], [films]),
    noun([laura], [lauras]),
    noun([magic], [magics]),
    noun([ms], [mss]),
    noun([programme], [programmes]),
    noun([student], [students]),
    noun([time], [times]),
    tv([is], [be]),
    tv([presents], [present]),
    tv([was], [be]),
    tv([be], [be]),
    tvPrep([trained], [as], [train], [todooo])
                     ])).


problem(baggage_mishaps, problem(4, 3, [
        "the three girls are savannah , the american with the yellow suitcase and the one traveling to america . ",
        "carmelita wants her suitcase to stand out , so she is not the person with the black suitcase . ",
        "of the girl with the lovely yellow suitcase and savannah , one is traveling to panama and the other is the american citizen . ",
        "gloria is neither the american citizen nor the one going to france , and she does not have a black suitcase . "
                     ], [
    pn([america]),
    pn([american]),
    pn([black]),
    pn([carmelita]),
    pn([france]),
    pn([francen]),
    pn([gloria]),
    pn([green]),
    pn([panama]),
    pn([panaman]),
    pn([savannah]),
    pn([yellow]),
    noun([citizen], [citizens]),
    noun([girl], [girls]),
    noun([person], [people]),
    noun([suitcase], [suitcases]),
    noun([traveling], [travelings]),
    tv([stand], [stand]),
    tv([is], [be]),
    tv([are], [be]),
    tv([traveling], [travele]),
    tv([wants], [want]),
    tv([going], [go])
                     ])).


problem(planetary_gazing, problem(4, 4, [
        "the person who moved to tampa is not jill . ",
        "the friend with the $ 122000 salary is sally . ",
        "the friend who moved to tampa did not observe saturn or mercury through her telescope . ",
        "the friend who moved to houston earns less than her friend in tampa . ",
        "the friend with the $ 95000 salary now lives in los angles . ",
        "either the friend living in los angles or the friend who moved to houston caught a great view of jupiter through her telescope . ",
        "the friend who 's job is in houston is not jill and she did not observe saturn through her telescope . ",
        "the friend who lives in tampa earns more than the friend who pointed her telescope at jupiter . ",
        "the woman living in los angles did not observe mercury through her telescope and is not jill . ",
        "of joann and the amateur astronomer who pointed her telescope at saturn , one now lives in houston and the other earns $ 56000 per year . ",
        "the one with the $ 122000 salary did not observe mercury through her telescope . ",
        "the person living near in tampa is not joann . ",
        "the person who found employment in detroit is not becky . "
                     ], [
    pn([becky]),
    pn([detroit]),
    pn([houston]),
    pn([jill]),
    pn([joann]),
    pn([jupiter]),
    pn([los, angles]),
    pn([mars]),
    pn([mercury]),
    pn([sally]),
    pn([saturn]),
    pn([tampa]),
    noun([astronomer], [astronomers]),
    noun([caught], [caughts]),
    noun([employment], [employments]),
    noun([friend], [friends]),
    noun([job], [jobs]),
    noun([living], [livings]),
    noun([one], [ones]),
    noun([person], [people]),
    noun([salary], [salaries]),
    noun([telescope], [telescopes]),
    noun([view], [views]),
    noun([woman], [women]),
    noun([year], [years]),
    tv([earns], [earn]),
    tv([found], [find]),
    tv([pointed], [point]),
    tv([observe], [observe]),
    tv([moved], [move]),
    tvPrep([is], [in], [be], [todooo]),
    tvPrep([lives], [in], [live], [todooo]),
    tvPrep([living], [near], [live], [todooo])
                     ])).


problem(bart, problem(4, 4, [
        "the 4 people were tatum , the patient who was prescribed enalapril , the person who earns 54000 , and the person who owns the purple house ",
        "of tatum and annabelle , one earns 144000 per year and the other lives in the cyan house ",
        "the patient who was prescribed enalapril is not heather ",
        "either the employee who earns 144000 or the employee who earns 158000 lives in the blue house ",
        "kassidy earns less than heather ",
        "the owner of the blue house earns more than kassidy ",
        "the patient who was prescribed ramipril is not annabelle ",
        "the owner of the lime house was prescribed enalapril for their heart condition ",
        "the employee who earns 144000 was prescribed benazepril for their heart condition "
                     ], [
    pn([annabelle]),
    pn([benazepril]),
    pn([blue]),
    pn([cyan]),
    pn([enalapril]),
    pn([fosinopril]),
    pn([heather]),
    pn([kassidy]),
    pn([lime]),
    pn([purple]),
    pn([ramipril]),
    pn([tatum]),
    noun([condition], [conditions]),
    noun([employee], [employees]),
    noun([heart], [hearts]),
    noun([house], [houses]),
    noun([life], [lives]),
    noun([owner], [owners]),
    noun([patient], [patients]),
    noun([person], [people]),
    noun([year], [years]),
    tv([earns], [earn]),
    tv([is], [be]),
    tv([was, prescribed], [be]),
    tv([were], [be]),
    tv([owns], [own])
                     ])).


problem(be_my_valentine, problem(4, 3, [
        "unluckily for freddie , when miss jetson received her card , she thought it was from adam . ",
        "when molly received her blue colored card , she told miss hanson and together they worked out who the card was from . it did not occur to either of them that it was from freddie . ",
        "the girl who received the red card was convinced it came from ethan . ",
        "neither millie nor miss motson received a pink card . "
                     ], [
    pn([adam]),
    pn([blue]),
    pn([dylan]),
    pn([ethan]),
    pn([hanson]),
    pn([jetson]),
    pn([lily]),
    pn([millie]),
    pn([molly]),
    pn([motson]),
    pn([pink]),
    pn([red]),
    noun([card], [cards]),
    noun([freddie], [freddies]),
    noun([girl], [girls]),
    noun([miss], [misses]),
    tv([thought], [think]),
    tv([worked], [work]),
    tv([occur], [occur]),
    tv([told], [tell]),
    tv([colored], [colore]),
    tv([received], [receive]),
    tvPrep([came], [from], [come], [todooo]),
    tvPrep([was], [from], [be], [todooo])
                     ])).


problem(dragon_slayer, problem(4, 5, [
        "both sir percival and the knight who slew the welsh dragon had green in their colors ",
        "the knight that battled the ancient dragon wore colors of blue & white ",
        "neither sir dane or sir richard had green in their colors ",
        "sir gwain fought the irish dragon ",
        "the knight that slew the ancient dragon bore the shield . ",
        "the knights that carried an axe and a sword both had white in their colors ",
        "an arrow from the bow pierced the english dragon ",
        "one of the knights who had green in their colors carried the bow ",
        "both sir richard and sir gwain had red in their colors ",
        "the irish dragon was slain with a sword "
                     ], [
    pn([ancient]),
    pn([axe]),
    pn([blue, &, white]),
    pn([bow]),
    pn([english]),
    pn([green, &, gold]),
    pn([green, &, white]),
    pn([irish]),
    pn([mace]),
    pn([red, &, gold]),
    pn([red, &, white]),
    pn([scottish]),
    pn([shield]),
    pn([sir, dane]),
    pn([sir, gwain]),
    pn([sir, john]),
    pn([sir, percival]),
    pn([sir, richard]),
    pn([sword]),
    pn([welsh]),
    noun([arrow], [arrows]),
    noun([color], [colors]),
    noun([dragon], [dragons]),
    noun([knight], [knights]),
    tv([was, slain], [be]),
    tv([pierced], [pierce]),
    tv([battled], [battle]),
    tv([fought], [fight]),
    tv([wore], [wear]),
    tv([carried], [carry]),
    tvPrep([slain], [with], [slay], [todooo])
                     ])).


problem(kids_at_play, problem(4, 3, [
        "tommy was always upset to be called in for dinner before the other 2 boys ",
        "mrs jones never had dinner ready later than 600pm ",
        "of dickey and the jackson boy , one loved playing red light , green light and the other boy 's dinner was at 600pm sharp ",
        "the jackson boy did not like hide and seek as much as tommy ",
        "harry always had 15 alone once the others were called in ",
        "mr smith would have 15 minutes to read the newspaper after work before dinner was on the table at 530pm ",
        "dickey jones loved playing tag "
                     ], [
    pn([dickey]),
    pn([harry]),
    pn([hide/seek]),
    pn([jackson]),
    pn([jones]),
    pn([red, light]),
    pn([smith]),
    pn([tag]),
    pn([tommy]),
    noun([boy], [boys]),
    noun([dinner], [dinners]),
    noun([hide], [hides]),
    noun([minute], [minutes]),
    noun([mr], [mrs]),
    noun([mrs], [mrss]),
    noun([newspaper], [newspapers]),
    noun([other], [others]),
    noun([playing], [playings]),
    noun([table], [tables]),
    noun([work], [works]),
    tv([like], [like]),
    tv([read], [read]),
    tv([playing], [play]),
    tv([seek], [seek]),
    tv([upset], [upset]),
    tv([loved], [love]),
    tvPrep([called], [in], [call], [todooo]),
    tvPrep([was], [at], [be], [todooo]),
    tvPrep([was], [on], [be], [todooo])
                     ])).


problem(classroom_blues, problem(4, 3, [
        "the student being moved farthest from the front of the classroom gets in trouble for throwing airplanes . ",
        "mr williams taught his son how to build paper airplanes . ",
        "gloria has a hard time staying awake in class . ",
        "raymond pierce is being moved closest to the door . "
                     ], [
    pn([back, row]),
    pn([front, row]),
    pn([gloria]),
    pn([michael]),
    pn([near, door]),
    pn([pierce]),
    pn([raymond]),
    pn([sharp]),
    pn([sleeping]),
    pn([talking]),
    pn([throwing]),
    pn([williams]),
    noun([airplane], [airplanes]),
    noun([awake], [awakes]),
    noun([class], [classes]),
    noun([classroom], [classrooms]),
    noun([paper], [papers]),
    noun([son], [sons]),
    noun([student], [students]),
    noun([time], [times]),
    noun([trouble], [troubles]),
    tv([is], [be]),
    tv([staying], [stay]),
    tv([build], [build]),
    tv([taught], [teach]),
    tv([being, moved], [be]),
    tvPrep([gets], [in], [get], [todooo])
                     ])).


problem(trick_or_treating, problem(5, 4, [
        "of the 4 children , there was the 8 year old , the child who dressed as a werewolf , the child who was accompanied by their sister , and the one who carried the red flashlight . ",
        "between the 9 year old and frank , who is older than toby , one was dressed as a goblin and the other carried the green flashlight . ",
        "neither frank nor judy were accompanied by their sister while trick or treating . judy did not carry an orange flashlight . ",
        "toby 's mother was upset that he cut up one of her favorite sheets to create his ghost costume . ",
        "the child who dressed as a werewolf was accompanied by a male and did not carry a green flashlight . ",
        "the nine year old was quite happy with her goblin costume which she spent an entire week designing . ",
        "either frank or toby carried a green flashlight . ",
        "the child who was accompanied by their brother was exactly 2 years older than the child who went with their sister . ",
        "jessica caught her uncle sneaking candy from her bag while they walked ! ",
        "the child dressed as a ghost carried a blue flashlight . "
                     ], [
    pn([aunt]),
    pn([blue]),
    pn([brother]),
    pn([frank]),
    pn([ghost]),
    pn([goblin]),
    pn([green]),
    pn([jessica]),
    pn([judy]),
    pn([orange]),
    pn([red]),
    pn([sister]),
    pn([toby]),
    pn([uncle]),
    pn([vampire]),
    pn([werewolf]),
    noun([bag], [bags]),
    noun([candy], [candies]),
    noun([child], [children]),
    noun([costume], [costumes]),
    noun([designing], [designings]),
    noun([flashlight], [flashlights]),
    noun([male], [males]),
    noun([mother], [mothers]),
    noun([one], [ones]),
    noun([sheet], [sheets]),
    noun([treating], [treatings]),
    noun([trick], [tricks]),
    noun([week], [weeks]),
    noun([year], [years]),
    tv([was, accompanied], [be]),
    tv([was, upset], [be]),
    tv([was, dressed], [be]),
    tv([is], [be]),
    tv([caught], [catch]),
    tv([sneaking], [sneak]),
    tv([walked], [walk]),
    tv([carry], [carry]),
    tv([spent], [spend]),
    tv([create], [create]),
    tv([carried], [carry]),
    tv([was], [be]),
    tv([cut], [cut]),
    tv([were, accompanied], [be]),
    tvPrep([accompanied], [by], [accompany], [todooo]),
    tvPrep([dressed], [as], [dress], [todooo]),
    tvPrep([upset], [that], [upset], [todooo]),
    tvPrep([went], [with], [go], [todooo])
                     ])).


problem(greek_dogs, problem(4, 5, [
        "the 5 people were jenny , the person married in 1929 , the person with the att cell phone , the person who named their dog cassiopeia , and julie ",
        "the person with the sprint cell phone got married after the person who named their dog agamemnon . ",
        "the person who named their dog hephaestus got married before the person who named their dog agamemnon . ",
        "the person who named their dog cassiopeia got married after the person with the tmobile cell phone . ",
        "the person with the att cell phone is not jason . ",
        "the person married in 1976 is james . ",
        "of the person with the sprint cell phone and jason , one got married in 1946 and the other named their dog agamemnon . ",
        "the person married in 1982 named their dog lycurgus . ",
        "the person who named their dog lycurgus is not josie or jenny . ",
        "either the person with the nextel cell phone or the person with the sprint cell phone is james . "
                     ], [
    pn([agamemnon]),
    pn([att]),
    pn([cassiopeia]),
    pn([endymion]),
    pn([hephaestus]),
    pn([james]),
    pn([jason]),
    pn([jenny]),
    pn([josie]),
    pn([julie]),
    pn([lycurgus]),
    pn([nextel]),
    pn([sprint]),
    pn([tmobile]),
    pn([verizon]),
    noun([cell], [cells]),
    noun([dog], [dogs]),
    noun([person], [people]),
    noun([phone], [phones]),
    tv([got, married], [get]),
    tv([were], [be]),
    tv([named], [name]),
    tvPrep([married], [after], [marry], [todooo]),
    tvPrep([married], [before], [marry], [todooo]),
    tvPrep([married], [in], [marry], [todooo]),
    tvGap([is], [james], [be])
                     ])).


problem(time_to_quit, problem(4, 5, [
        "the 5 people were the person who grows kiwis , the employee whose last day will be july 8 , the people subscriber , trenton , and the person who grows guavas . ",
        "the time subscriber will leave before the newsweek subscriber . ",
        "the time subscriber does not grow guavas . ",
        "the time subscriber will leave before ricky . ",
        "of trenton and the person who grows apples , one is leaving the company on september 23 and the other subscribed to usweekly . ",
        "the person who grows boysenberries is trenton . ",
        "bianca will leave after roger . ",
        "the newsweek subscriber is not ricky . ",
        "the person who grows kiwis is not roger . ",
        "either the employee whose last day will be january 13 or the employee whose last day will be september 23 grows strawberries . ",
        "the usweekly subscriber is bianca . "
                     ], [
    pn([apples]),
    pn([august, 8]),
    pn([bianca]),
    pn([boysenberries]),
    pn([charlie]),
    pn([fortune]),
    pn([guavas]),
    pn([january, 13]),
    pn([july, 8]),
    pn([kiwis]),
    pn([may, 28]),
    pn([newsweek]),
    pn([people]),
    pn([ricky]),
    pn([roger]),
    pn([september, 23]),
    pn([strawberries]),
    pn([time]),
    pn([trenton]),
    pn([us, weekly]),
    noun([company], [companies]),
    noun([day], [days]),
    noun([employee], [employees]),
    noun([grow], [grows]),
    noun([person], [people]),
    noun([subscriber], [subscribers]),
    tv([grows], [grow]),
    tv([were], [be]),
    tv([usweekly], [usweekly]),
    tv([is], [be]),
    tv([subscriber], [subscriber]),
    tv([subscribed], [subscribe]),
    tv([grow], [grow]),
    tv([be], [be]),
    tvPrep([leave], [after], [leave], [todooo]),
    tvPrep([leave], [before], [leave], [todooo])
                     ])).


problem(breakfast_time, problem(4, 3, [
        "the person who read the newspaper had breakfast later than the person who liked to listen to the news on the radio . ",
        "jennifer had her breakfast directly before the person who had toast . ",
        "cereal was eaten 20 minutes after the person who watched the breakfast news on tv . ",
        "claudia 's black coffee was not the breakfast taken last . "
                     ], [
    pn([cereal]),
    pn([claudia]),
    pn([coffee]),
    pn([jennifer]),
    pn([newspaper]),
    pn([radio]),
    pn([steph]),
    pn([television]),
    pn([toast]),
    noun([breakfast], [breakfasts]),
    noun([minute], [minutes]),
    noun([news], [news]),
    noun([person], [people]),
    noun([tv], [tvs]),
    tv([listen], [listen]),
    tv([read], [read]),
    tv([liked], [like]),
    tv([was], [be]),
    tv([taken], [take]),
    tv([watched], [watch])
                     ])).


problem(piracy, problem(4, 3, [
        "the saucy sue is not the ship of the buccaneer who lost his left hand and who spent 4 years living on coconut milk and fish . ",
        "the buccaneer with only one eye spent the longest time marooned but was not captain stump . ",
        "mean mike lost a leg after a cutlass wound went septic . ",
        "grey beard 's ship is called big bess . "
                     ], [
    pn([big, bess]),
    pn([captain, stump]),
    pn([eye]),
    pn([grey, beard]),
    pn([hand]),
    pn([leg]),
    pn([mean, mike]),
    pn([merry, rose]),
    pn([suacy, sue]),
    noun([buccaneer], [buccaneers]),
    noun([coconut], [coconuts]),
    noun([cutlass], [cutlasses]),
    noun([fish], [fish]),
    noun([milk], [milks]),
    noun([saucy], [saucies]),
    noun([ship], [ships]),
    noun([time], [times]),
    noun([wound], [wounds]),
    noun([year], [years]),
    tv([is, called], [be]),
    tv([is], [be]),
    tv([went], [go]),
    tv([spent], [spend]),
    tv([lost], [lose]),
    tv([was], [be]),
    tv([marooned], [maroon]),
    tvPrep([living], [on], [live], [todooo])
                     ])).


problem(breakfast_at_tiffanys, problem(4, 4, [
        "samantha had a bowl of cereal but not a latte . ",
        "the friend who ordered the potato pancakes also ordered a coffee to go but did not have an ice tea . ",
        "the woman who ordered the omelet had apple juice to drink but she was not jenny . ",
        "of the two friends who ordered the orange juice and the ice tea , one was jackie and the other was the friend who ordered the french toast . ",
        "the friend who ordered a bottle of water to go did not order orange juice . ",
        "judy ordered a lemonade to go . "
                     ], [
    pn([apple, juice]),
    pn([cereal]),
    pn([chocolate, milk]),
    pn([coffee]),
    pn([french, toast]),
    pn([ice, tea]),
    pn([jackie]),
    pn([jenny]),
    pn([judy]),
    pn([latte]),
    pn([lemonade]),
    pn([omlet]),
    pn([orange, juice]),
    pn([pancakes]),
    pn([samantha]),
    pn([water]),
    noun([bottle], [bottles]),
    noun([bowl], [bowls]),
    noun([friend], [friends]),
    noun([omelet], [omelets]),
    noun([order], [orders]),
    noun([potato], [potatoes]),
    noun([woman], [women]),
    tv([drink], [drink]),
    tv([ordered], [order]),
    tv([was], [be]),
    tv([go], [go])
                     ])).


problem(beach_bum, problem(4, 4, [
        "alexandra found a lovely sharks tooth 3 years after the souvenir she bought on topsail island . ",
        "the conch shell was not found in 2007 . ",
        "of the souvenir she purchased in 2013 and the one she bought in long beach , one is the sharks tooth and the other was purchased at saltys marina ",
        "she simply could not resist the hula girl that swayed back and forth that she saw either while she was in santa barbara , or while staying on topsail island . ",
        "while on south padre island , she either purchased the hula girl or visited island gifts . ",
        "she either purchased the pearl bracelet in 2004 , or while she was browsing at ocean treasures . ",
        "neither the souvenir purchased while on south padre island , nor the conch shell is the souvenir found in 2004 . ",
        "the souvenir she found while on topsail island was not from ocean treasures . "
                     ], [
    pn([beach, bum]),
    pn([conch, shell]),
    pn([hula, girl]),
    pn([island, gifts]),
    pn([long, beach]),
    pn([ocean, treasur]),
    pn([pearl, bracele]),
    pn([saltys, marina]),
    pn([santa, barbara]),
    pn([sharks, tooth]),
    pn([south, padre]),
    pn([topsail]),
    noun([alexandra], [alexandras]),
    noun([bracelet], [bracelets]),
    noun([forth], [forths]),
    noun([souvenir], [souvenirs]),
    noun([treasure], [treasures]),
    noun([year], [years]),
    tv([saw], [see]),
    tv([swayed], [sway]),
    tv([visited], [visit]),
    tv([resist], [resist]),
    tvPrep([bought], [in], [buy], [todooo]),
    tvPrep([bought], [on], [buy], [todooo]),
    tvPrep([browsing], [at], [browse], [todooo]),
    tvPrep([found], [in], [find], [todooo]),
    tvPrep([found], [while], [find], [todooo]),
    tvPrep([purchased], [at], [purchase], [todooo]),
    tvPrep([purchased], [in], [purchase], [todooo]),
    tvPrep([purchased], [while], [purchase], [todooo]),
    tvPrep([staying], [on], [stay], [todooo]),
    tvPrep([was], [in], [be], [todooo])
                     ])).


problem(pet_or_no_pet, problem(4, 3, [
        "neither girl lives in the odd-numbered house . ",
        "the spaniel does not live at number 24 , nor with sammy . ",
        "sarah , who is not the oldest , lives furthest from number 15 . ",
        "the girl whose age and house number match does not have a pet . "
                     ], [
    pn([no, pet]),
    pn([sally]),
    pn([sammy]),
    pn([sarah]),
    pn([spaniel]),
    pn([terrier]),
    noun([age], [ages]),
    noun([girl], [girls]),
    noun([house], [houses]),
    noun([match], [matches]),
    noun([number], [numbers]),
    tv([is], [be]),
    tvPrep([live], [at], [live], [todooo]),
    tvPrep([lives], [in], [live], [todooo])
                     ])).


% cookies_for_love, expensive_homes, at_the_farm, tutorial, new_shoes, cats_in_spring, a_bargain, class_is_in, remodeling_fun, christmas_presents, p1_json, star_students, baggage_mishaps, planetary_gazing, bart, be_my_valentine, dragon_slayer, kids_at_play, classroom_blues, trick_or_treating, greek_dogs, time_to_quit, breakfast_time, piracy, breakfast_at_tiffanys, beach_bum, pet_or_no_pet
